# Artificial Neural Networks

## Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
tf.__version__

'2.19.0'

## Data Preprocessing

### Importing the dataset

In [3]:
df = pd.read_csv("Churn_Modelling.csv")
X = df.iloc[:,3:-1].values
y = df.iloc[:,-1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding the categorical data

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


#### One hot encoding to 'Geography' column

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[1])],remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into training set & test set

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)

### Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
print(X_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


In [13]:
print(X_test)

[[-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
   1.61085707]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   0.49587037]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   0.71888467]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -1.54507805]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   1.61255917]]


In [14]:
print(y_train)

[0 0 0 ... 0 0 1]


In [15]:
print(y_test)

[0 1 0 ... 0 0 0]


## Building the ANN

### Initialising the ANN

In [16]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [17]:
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))

### Adding the second hidden layer

In [18]:
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))

### Adding the output layer

In [19]:
ann.add(tf.keras.layers.Dense(units = 1,activation = 'sigmoid'))

## Training the ANN

### Compiling the ANN

In [20]:
ann.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

### Training the ANN on the training set

In [21]:
ann.fit(X_train,y_train,batch_size = 32,epochs = 100)

Epoch 1/100


250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 719us/step - accuracy: 0.5306 - loss: 0.7211
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 602us/step - accuracy: 0.7997 - loss: 0.5105
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 658us/step - accuracy: 0.7966 - loss: 0.4754
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 599us/step - accuracy: 0.8127 - loss: 0.4328
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 640us/step - accuracy: 0.8115 - loss: 0.4302
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 724us/step - accuracy: 0.8101 - loss: 0.4343
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 732us/step - accuracy: 0.8239 - loss: 0.4142
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 652us/step - accuracy: 0.8195 - loss: 0.4143
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 707us/step - accuracy: 0.8290 - loss: 0.3975
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.8379 - loss: 0.3850
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.8373 - loss: 0.3785
Epoch 12/100
250/250 ━━━━━━━━━━

## Making the predictions and evaluating the model

### Predicting the result of a single observation

Geography = France
Credit_score = 600
Gender = Male
Age = 40 years old
Tenure = 3 years
Balance = $60000
No. of products = 2
Does this costomer have a credit card = yes
Is this costomer an active member = yes
Estimated salary = $50000
So, should we say good bye to that costomer?

In [23]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
[[False]]


### Predicting the Test set results

In [24]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 581us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the confusion matrix

In [25]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1513   82]
 [ 194  211]]


0.862